# Generated by Django 5.2.1 on 2025-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiassistant',
            name='created_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
