# Generated by Django 5.2.1 on 2025-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0002_alter_openaiassistant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiassistant',
            name='tool_resources',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
