# Generated by Django 5.2.1 on 2025-06-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachAsistant', '0003_openaiassistant_tool_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiassistant',
            name='tool_resources',
            field=models.JSONField(blank=True, default=dict, help_text='Ресурсы для инструментов в формате: {"file_search": {"vector_store_ids": ["vs_123"]}}'),
        ),
    ]
